my_app_filmotheque_homepage:
    path:     /index/{name}
    defaults: { _controller: "MyAppFilmothequeBundle:Default:index" }
myapp_acteur_lister:
  pattern: /acteur/
  defaults: { _controller: "MyAppFilmothequeBundle:Acteur:lister" }
myapp_acteur_ajouter:
  pattern: /acteur/ajouter
  defaults: { _controller: "MyAppFilmothequeBundle:Acteur:ajouter" }
myapp_acteur_modifier:
  pattern: /acteur/modifier/{id}
  defaults: { _controller: "MyAppFilmothequeBundle:Acteur:modifier" }
myapp_acteur_supprimer:
  pattern: /acteur/supprimer/{id}
  defaults: { _controller: "MyAppFilmothequeBundle:Acteur:supprimer" }
    